new records
BetaMasaheft/Institutions pull request #20
Opened 2020-12-09 14:46 UTC by thea-m

https://github.com/BetaMasaheft/Documentation/issues/1327
To have a starting point, much can be improved

2021-01-07 14:50 UTC, thea-m commented
@DenisNosnitsin1970

2021-01-07 14:59 UTC, DenisNosnitsin1970 requested changes

2021-01-07 14:59 UTC, DenisNosnitsin1970 commented on new/INS0922AbiyaEgzi.xml
> +                <title>ʾAbbā ʿĀbiya ʾƎgziʾ (Kidāna Məḥrat)</title>
I think you can take as the name here Abba Abiya Egzi, or add Kidana Mehrat without brackets.

2021-01-12 10:54 UTC, thea-m commented
Thank you!

2021-01-13 16:09 UTC, merged