INS0992 0992
BetaMasaheft/Institutions pull request #68
Opened 2022-12-30 14:16 UTC by DenisNosnitsin1970

Two new records, one for the Übersee Museum on Fehmarn, another for the Serbian National Library, where up to 4 or 5 Ethiopic mss have turned up.

2022-12-30 17:17 UTC, eu-genia approved these changes

2023-01-02 10:04 UTC, thea-m requested changes

2023-01-02 10:23 UTC, DenisNosnitsin1970 commented on new/INS0991Serbian.xml
> +                    <placeName xml:id="n2" xml:lang="sr">Народна библиотека Србије</placeName>
I thought the same, but when I include  `<language ident="sr">Gǝʿǝz</language> ` the system reports a mistake.

2023-01-02 10:23 UTC, DenisNosnitsin1970 commented on new/INS0992UeberseeFehmarn.xml
> +                    <relation name="saws:hasOwned" active="INS0992UeberseeFehmarn" passive="MUFet01"/>
ok

2023-01-02 10:42 UTC, eu-genia commented on new/INS0991Serbian.xml
> +                    <placeName xml:id="n2" xml:lang="sr">Народна библиотека Србије</placeName>
Of course if sr is not in the taxonomy.

2023-01-02 10:53 UTC, DenisNosnitsin1970 commented on new/INS0991Serbian.xml
> +                    <placeName xml:id="n2" xml:lang="sr">Народна библиотека Србије</placeName>
Does it mean, one of the files in "Schema" folder should be changed? I see there is a list of languages in tei-betamasaheft.xml file. Should "sr" be included there?

2023-01-02 10:58 UTC, thea-m commented on new/INS0991Serbian.xml
> +                    <placeName xml:id="n2" xml:lang="sr">Народна библиотека Србије</placeName>
yes, here is the guide: https://betamasaheft.eu/Guidelines/?id=editingSchema
(contrary to what I said first, the taxonomy does not need to be updated)

2023-01-04 13:02 UTC, merged